name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    # Step 4: 打包为 .exe 文件
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --noconsole get_iphone_v2.py
        echo "Contents of dist directory:"
        ls -R dist/
        if [ -z "$(ls -A dist/)" ]; then
          echo "Error: dist directory is empty!"
          exit 1
        fi

    # Step 5: 上传构建产物
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: iphone_v2
        path: ${{ github.workspace }}/dist/
