name: Build Windows Executable

on:
  push:
    branches:
      - main  # 替换为你的实际分支名称
  pull_request:
    branches:
      - main  # 替换为你的实际分支名称
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 运行器

    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    # Step 4: 打包为 .exe 文件
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --noconsole get_iphone_v2.py

    # Step 5: 验证 dist 目录
    - name: Verify dist directory
      run: |
        echo "Contents of dist directory:"
        ls -R dist/
        if [ -z "$(ls -A dist/)" ]; then
          echo "Error: dist directory is empty!"
          exit 1
        fi

    # Step 6: 安装阿里云 CLI
    - name: Install Aliyun CLI
      run: |
        curl -O https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz
        tar -xzf aliyun-cli-linux-latest-amd64.tgz
        sudo mv aliyun /usr/local/bin/

    # Step 7: 配置阿里云 CLI
    - name: Configure Aliyun CLI
      run: >
        aliyun configure set --profile akProfile
        --mode AK
        --access-key-id ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        --access-key-secret ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        --region oss-cn-guangzhou

    # Step 8: 上传到 OSS
    - name: Upload to OSS
      run: |
        aliyun oss cp dist/get_iphone_v2.exe oss://your-bucket-name/
